<a href="https://colab.research.google.com/github/zainamri/kumpulantugas/blob/main/tgs3textmining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas 3 Zain (15230008)
Preprocessing

In [ ]:
!pip install pandas nltk Sastrawi

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: Sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [ ]:
nltk.download('punkt_tab')
nltk.download('stopwords')

stop_words = set(stopwords.words('indonesian'))

factory = StemmerFactory()
stemmer = factory.create_stemmer()

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
# Membuka data yang sudah ditarik dari YouTube
df = pd.read_csv('/content/komentar_deforestasipapua.csv')

print("Data Asli (Sebelum Dibersihkan):")
display(df[['Teks Komentar']].head())

Data Asli (Sebelum Dibersihkan):

                                       Teks Komentar
0  Rapatkan barisan semua suku di papua,untuk ber...
1  Baru sadar bahwa pemerintah konoha itu penjaja...
2  Salam Kenal KK,.. Saya senang sekali nonton vi...
3                         PAPUA BUKAN TANAH KOSONG!!
4   https://youtu.be/Nf2OVkfLRLg?si=9Y1sJ-rbT3tYnIK3

In [ ]:
# Mengubah semua huruf menjadi kecil
df['text_lower'] = df['Teks Komentar'].astype(str).str.lower()

print("Hasil Case Folding:")
display(df[['Teks Komentar', 'text_lower']].head())

Hasil Case Folding:

,Teks Komentar,text_lower
0,"Rapatkan barisan semua suku di papua,untuk ber...","rapatkan barisan semua suku di papua,untuk ber..."
1,Baru sadar bahwa pemerintah konoha itu penjaja...,baru sadar bahwa pemerintah konoha itu penjaja...
2,"Salam Kenal KK,.. Saya senang sekali nonton vi...","salam kenal kk,.. saya senang sekali nonton vi..."
3,PAPUA BUKAN TANAH KOSONG!!,papua bukan tanah kosong!!
4,https://youtu.be/Nf2OVkfLRLg?si=9Y1sJ-rbT3tYnIK3,https://youtu.be/nf2ovkflrlg?si=9y1sj-rbt3tynik3

In [ ]:
# Fungsi untuk menghapus selain huruf a-z dan spasi
def clean_punctuation(text):
    return re.sub(r'[^a-z\s]', '', text)

df['text_clean'] = df['text_lower'].apply(clean_punctuation)

print("Hasil Cleaning Tanda Baca:")
display(df[['text_lower', 'text_clean']].head())

Hasil Cleaning Tanda Baca:

,text_lower,text_clean
0,"rapatkan barisan semua suku di papua,untuk ber...",rapatkan barisan semua suku di papuauntuk bert...
1,baru sadar bahwa pemerintah konoha itu penjaja...,baru sadar bahwa pemerintah konoha itu penjaja...
2,"salam kenal kk,.. saya senang sekali nonton vi...",salam kenal kk saya senang sekali nonton video...
3,papua bukan tanah kosong!!,papua bukan tanah kosong
4,https://youtu.be/nf2ovkflrlg?si=9y1sj-rbt3tynik3,httpsyoutubenfovkflrlgsiysjrbttynik

In [ ]:
# Kamus bahasa gaul
slang_dict = {
    "gk": "tidak",
    "ga": "tidak",
    "gak": "tidak",
    "bgt": "banget",
    "banget": "sangat",
    "yg": "yang",
    "klo": "kalau",
    "tp": "tapi",
    "thn": "tahun",
    "dgn": "dengan"
}

def normalize_slang(text):
    words = text.split()
    return " ".join([slang_dict.get(word, word) for word in words])

df['text_slang'] = df['text_clean'].apply(normalize_slang)

print("Hasil Perbaikan Bahasa Gaul:")
display(df[['text_clean', 'text_slang']].head())

Hasil Perbaikan Bahasa Gaul:

,text_clean,text_slang
0,rapatkan barisan semua suku di papuauntuk bert...,rapatkan barisan semua suku di papuauntuk bert...
1,baru sadar bahwa pemerintah konoha itu penjaja...,baru sadar bahwa pemerintah konoha itu penjaja...
2,salam kenal kk saya senang sekali nonton video...,salam kenal kk saya senang sekali nonton video...
3,papua bukan tanah kosong,papua bukan tanah kosong
4,httpsyoutubenfovkflrlgsiysjrbttynik,httpsyoutubenfovkflrlgsiysjrbttynik

In [ ]:
# Memotong kalimat menjadi kata per kata
df['tokens'] = df['text_slang'].apply(word_tokenize)

print("Hasil Tokenisasi:")
display(df[['text_slang', 'tokens']].head())

Hasil Tokenisasi:

,text_slang,tokens
0,rapatkan barisan semua suku di papuauntuk bert...,"[rapatkan, barisan, semua, suku, di, papuauntu..."
1,baru sadar bahwa pemerintah konoha itu penjaja...,"[baru, sadar, bahwa, pemerintah, konoha, itu, ..."
2,salam kenal kk saya senang sekali nonton video...,"[salam, kenal, kk, saya, senang, sekali, nonto..."
3,papua bukan tanah kosong,"[papua, bukan, tanah, kosong]"
4,httpsyoutubenfovkflrlgsiysjrbttynik,[httpsyoutubenfovkflrlgsiysjrbttynik]

In [ ]:
# Membuang kata tidak penting
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['tokens_stop'] = df['tokens'].apply(remove_stopwords)

print("Hasil Stopword Removal:")
display(df[['tokens', 'tokens_stop']].head())

Hasil Stopword Removal:

,tokens,tokens_stop
0,"[rapatkan, barisan, semua, suku, di, papuauntu...","[rapatkan, barisan, suku, papuauntuk, bertinda..."
1,"[baru, sadar, bahwa, pemerintah, konoha, itu, ...","[sadar, pemerintah, konoha, penjajah, pulau, e..."
2,"[salam, kenal, kk, saya, senang, sekali, nonto...","[salam, kenal, kk, senang, nonton, video, kk, ..."
3,"[papua, bukan, tanah, kosong]","[papua, tanah, kosong]"
4,[httpsyoutubenfovkflrlgsiysjrbttynik],[httpsyoutubenfovkflrlgsiysjrbttynik]

In [ ]:
# Mencari kata dasar
def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

print("Mesin sedang mengupas kata... tunggu sebentar ya!")
df['tokens_stem'] = df['tokens_stop'].apply(stemming)

print("\n Hasil Stemming:")
display(df[['tokens_stop', 'tokens_stem']].head())

Mesin sedang mengupas kata... tunggu sebentar ya!

 Hasil Stemming:

,tokens_stop,tokens_stem
0,"[rapatkan, barisan, suku, papuauntuk, bertinda...","[rapat, baris, suku, papuauntuk, tindak, melaw..."
1,"[sadar, pemerintah, konoha, penjajah, pulau, e...","[sadar, perintah, konoha, jajah, pulau, etnis,..."
2,"[salam, kenal, kk, senang, nonton, video, kk, ...","[salam, kenal, kk, senang, nonton, video, kk, ..."
3,"[papua, tanah, kosong]","[papua, tanah, kosong]"
4,[httpsyoutubenfovkflrlgsiysjrbttynik],[httpsyoutubenfovkflrlgsiysjrbttynik]

In [ ]:
# Menyatukan kata menjadi teks utuh kembali
df['final_text'] = df['tokens_stem'].apply(lambda x: ' '.join(x))

print("Hasil Akhir Teks Bersih:")
display(df[['Teks Komentar', 'final_text']].head())

# Menyimpan data untuk dilabeli secara manual
df_untuk_dilabeli = df[['Teks Komentar', 'final_text']]
df_untuk_dilabeli.to_csv('data_siap_label.csv', index=False)

print("\nBerhasil! File 'data_siap_label.csv' sudah tersimpan di folder sebelah kiri.")

Hasil Akhir Teks Bersih:

,Teks Komentar,final_text
0,"Rapatkan barisan semua suku di papua,untuk ber...",rapat baris suku papuauntuk tindak melawanjang...
1,Baru sadar bahwa pemerintah konoha itu penjaja...,sadar perintah konoha jajah pulau etnis sejaht...
2,"Salam Kenal KK,.. Saya senang sekali nonton vi...",salam kenal kk senang nonton video kk dorang l...
3,PAPUA BUKAN TANAH KOSONG!!,papua tanah kosong
4,https://youtu.be/Nf2OVkfLRLg?si=9Y1sJ-rbT3tYnIK3,httpsyoutubenfovkflrlgsiysjrbttynik

Berhasil! File 'data_siap_label.csv' sudah tersimpan di folder sebelah kiri.

In [ ]:
import pandas as pd

# Membuka data yang tadi
df = pd.read_csv('data_siap_label.csv')

# Membuat kamus sederhana untuk penilaian otomatis
pos_words = ['bagus', 'baik', 'cerdas', 'suka', 'mantap', 'menarik', 'hebat', 'keren', 'manfaat', 'setuju', 'luar biasa', 'recommended', 'penting', 'edukasi', 'cerah', 'maju', 'pintar', 'sukses', 'semangat', 'paham', 'nyambung', 'hormat', 'dukung', 'terbaik', 'solusi', 'bantu', 'berguna', 'wow']
neg_words = ['buruk', 'jelek', 'babi', 'kecewa', 'parah', 'lama', 'bodoh', 'tolol', 'goblok', 'bahaya', 'takut', 'ancam', 'kurang', 'salah', 'kacau', 'hancur', 'ngeri', 'pusing', 'susah', 'berat', 'bingung', 'tolak', 'anti', 'ancaman', 'rugi', 'gagal', 'sulit', 'malas']

# Fungsi penilai skor
def auto_label(text):
    if not isinstance(text, str):
        return 0
    words = text.split()

    # Hitung jumlah kata positif dan negatif
    pos_score = sum(1 for w in words if w in pos_words)
    neg_score = sum(1 for w in words if w in neg_words)

    # Beri label 1 (Positif) jika kata positif lebih banyak, sisanya 0 (Negatif)
    return 1 if pos_score >= neg_score else 0

# Terapkan fungsi pelabelan otomatis ke kolom 'final_text'
df['label'] = df['final_text'].apply(auto_label)

print("Proses pelabelan otomatis selesai!")
display(df[['final_text', 'label']].head(10))

# Menyimpan data yang sudah berlabel
df.to_csv('data_dilabeli.csv', index=False)
print("\nBagus! File 'data_dilabeli.csv' sudah berhasil dibuat.")

Proses pelabelan otomatis selesai!

                                          final_text  label
0  rapat baris suku papuauntuk tindak melawanjang...      1
1  sadar perintah konoha jajah pulau etnis sejaht...      0
2  salam kenal kk senang nonton video kk dorang l...      1
3                                 papua tanah kosong      1
4                httpsyoutubenfovkflrlgsiysjrbttynik      1
5                 ayo trendingkan papua tanah kosong      1
6                           pesta babi babi lg pesta      0
7  vincentttttttt layak bicara forum internasiona...      1
8                                ya allah jaga papua      1
9                                     mending mantap      1

Bagus! File 'data_dilabeli.csv' sudah berhasil dibuat.